const data = {
    products:[
        {
            _id:'1',
            name:'Harry Potter',
            author: 'J. K. Rowling',
            category: 'Children',
            image: '/images/p1.jpeg',
            price: 60,
            countInStock: 10,
            brand: 'Adidas',
            publishing: 'Arthur',
            rating: 4.5,
            numReviews: 10,
            description: 'aaaaaaaabakdjufcALIHCSA;',
        },
        {
            _id:'2',
            name:'Warriors',
            author: 'Erin Hunter',
            category: 'Children',
            image: '/images/p2.jpeg',
            price: 50,
            countInStock: 20,
            brand: 'Adidas',
            publishing: 'Arthur',
            rating: 4,
            numReviews: 10,
            description: 'aaaaaaaabakdjufcALIHCSA;',
        },
        {
            _id:'3',
            name:'The Little Prince',
            author: 'Antonie',
            category: 'Children',
            image: '/images/p3.jpeg',
            price: 90,
            countInStock: 0,
            brand: 'Adidas',
            publishing: 'Arthur',
            rating: 3,
            numReviews: 10,
            description: 'aaaaaaaabakdjufcALIHCSA;',
        },
        {
            _id:'4',
            name:'Pride and Prejudice',
            author:'Jane Austin',
            category: 'Romance',
            image: '/images/p4.jpeg',
            price: 60,
            countInStock: 50,
            brand: 'Adidas',
            publishing: 'Arthur',
            rating: 5,
            numReviews: 10,
            description: 'aaaaaaaabakdjufcALIHCSA;',
        },
        {
            _id:'5',
            name:'The Love Hypothesis',
            author: 'Ali Hazelwood',
            category: 'Romance',
            image: '/images/p5.jpeg',
            price: 60,
            countInStock: 5,
            brand: 'Adidas',
            publishing: 'Arthur',
            rating: 5,
            numReviews: 10,
            description: 'aaaaaaaabakdjufcALIHCSA;',
        },
        {
            _id:'6',
            name:'Jane Eyre',
            author: 'Charlotte ',
            category: 'Romance',
            image: '/images/p6.jpeg',
            price: 60,
            countInStock: 12,
            brand: 'Adidas',
            publishing: 'Arthur',
            rating: 5,
            numReviews: 13,
            description: 'aaaaaaaabakdjufcALIHCSA;',
        },
    ],
};
export default data;

